DB_HOST = 'labagh.pl'
DB_NAME = 's407396'  
DB_USER = 's407396'  
DB_PASSWORD = 'mkdaoz06rz7z' 

SECRET_KEY = 'dev'  
                   
JSON_SORT_KEYS = False
STATIC_FOLDER = '/home/s407396/public_html'  
BABEL_DEFAULT_LOCALE = 'en'
PAGINATION_PER_PAGE = 5
TEMPLATES_AUTO_RELOAD = True

SECURITY_PASSWORD_SALT = '167188741953294952065079255867006765106'  
SECURITY_USERNAME_ENABLE = True
SECURITY_USERNAME_REQUIRED = True
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = False
SECURITY_POST_REGISTER_VIEW = '/registered'

SESSION_COOKIE_DOMAIN = '.labagh.pl'
SESSION_COOKIE_HTTPONLY = False
